name: ci

on:
  push:
    branches:
      - main

jobs:
  console-app-1-unittests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Run Unit Tests for TestProject1.UnitTests
        run: dotnet test TestProject1.UnitTests/TestProject1.UnitTests.csproj
          
  build-console-app-1:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and test
        uses: docker/build-push-action@v5
        with:
          context: ConsoleApp1/.
          target: build
          load: true
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ConsoleApp1/.
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/testdocker:latest
