name: ci

on:
  push:
    branches:
      - main

jobs:
  console-app-1-unittests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      
      # Run unit tests for TestProject1.UnitTests
      -
        name: Run Unit Tests for TestProject1.UnitTests
        run: |
          dotnet test TestProject1.UnitTests/TestProject1.UnitTests.csproj

  console-app-1-unittests2:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      
      # Run unit tests for another test project (adjust the path as needed)
      -
        name: Run Unit Tests for AnotherTestProject.UnitTests
        run: |
          dotnet test AnotherTestProject.UnitTests/AnotherTestProject.UnitTests.csproj

  phases:
    build-and-test:
      jobs:
        - console-app-1-unittests
        - console-app-1-unittests2

  build-console-app-1:
    runs-on: ubuntu-latest
    needs: phases  # Wait for the entire build-and-test phase to complete
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and test
        run: |
          # Add your build and test commands here
          # For example:
          # docker build -t myimage .
          # docker run myimage tests
          echo "Building and testing the Docker image"

      # Add more steps as needed for your build and test process
