name: ci

on:
  push:
    branches:
      - main

jobs:
  console-app-1-unittests-1:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      
      # Run unit tests for TestProject1.UnitTests
      -
        name: Run Unit Tests for TestProject1.UnitTests
        run: dotnet test TestProject1.UnitTests/TestProject1.UnitTests.csproj
        
  console-app-1-unittests-2:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      
      # Run unit tests for TestProject1.UnitTests
      -
        name: Run Unit Tests for TestProject1.UnitTests
        run: dotnet test TestProject1.UnitTests/TestProject1.UnitTests.csproj

  build-console-app-1:
    runs-on: ubuntu-latest
    needs: [console-app-1-unittests-1, console-app-1-unittests-2]
    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
       -
        name: build console app 1
        run: dotnet run ConsoleApp1/ConsoleApp1.csproj
        
  build-console-app-1-dockercontainer:
    runs-on: ubuntu-latest
    needs: [console-app-1-unittests-1, console-app-1-unittests-2]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and test
        run: |
          # Add your build and test commands here
          # For example:
          # docker build -t myimage .
          # docker run myimage tests
          echo "Building and testing the Docker image"

      # Add more steps as needed for your build and test process
